{{- if .Values.lockbox.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bulletin-board.fullname" . }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.lockbox.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ include "bulletin-board.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: {{ .Values.lockbox.secretId | quote }}
        property: SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.lockbox.secretId | quote }}
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.lockbox.secretId | quote }}
        property: SPRING_DATASOURCE_PASSWORD
    - secretKey: STORAGE_S3_ACCESSKEY
      remoteRef:
        key: {{ .Values.lockbox.secretId | quote }}
        property: STORAGE_S3_ACCESSKEY
    - secretKey: STORAGE_S3_SECRETKEY
      remoteRef:
        key: {{ .Values.lockbox.secretId | quote }}
        property: STORAGE_S3_SECRETKEY
{{- end }}
