{{- if not .Values.lockbox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bulletin-board.fullname" . }}-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.secrets.datasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.datasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | quote }}
  STORAGE_S3_ACCESSKEY: {{ .Values.secrets.storageAccessKey | quote }}
  STORAGE_S3_SECRETKEY: {{ .Values.secrets.storageSecretKey | quote }}
{{- end }}
