apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: yandex-lockbox
spec:
  provider:
    yandexlockbox:
      apiEndpoint: https://lockbox.api.cloud.yandex.net
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: bulletin-board-lockbox-reader
            namespace: bulletin-board
