apiVersion: v1
kind: Service
metadata:
  name: bulletin-board
  namespace: bulletin-board
spec:
  selector:
    app: bulletin-board
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: management
      port: 9090
      targetPort: management
  type: LoadBalancer
